### ISSUE TITLE
Toggle fullscreen mode not fully working

### ISSUE THREAD

**Issue by hoangbossemo** [josejuanqm/VersaPlayer#9]
Can't not return to normal mode in fullscreen mode. pls check. Thank you

**Comment by josejuanqm** [comment]
Hi @hoangbossemo ,

Is the superview of the player removed after going into fullscreen mode?

**Comment by hemangshah** [comment]
@hoangbossemo - When you open an issue please always try to add as much information as possible so it may help the developer and contributors to understand the issue. You can also add screenshots, links to a video (describing the problem), or any content which you think you should share to help the developer and contributors to find a solution for you as quick as possible. 

With this always try to come back and give your update to the issue, you can add more information or close them. This will also help other users as well.

@josejuanqm - may be you can defined some guidelines on creating an issue and providing the information. Example - open an [issue](https://github.com/Alamofire/Alamofire/issues/new) for Alamofire.

P.S. I have decided to write this comment because I saw that you're very active in providing solution to your repo users. It's really appreciable. 👍🏼

**Comment by josejuanqm** [comment]
@hemangshah thanks a ton!

really appreciate your input. 
I'll work on implementing this!

**Comment by IpareSe** [comment]
> Hi @hoangbossemo ,
> 
> Is the superview of the player removed after going into fullscreen mode?

Yes I am facing this issue, once the player view enters in fullscreen mode. not able to return to superview. It does not restore the original frame.

**Comment by josejuanqm** [comment]
Thanks @IpareSe I'll look into this

**Comment by adaminspaceship** [comment]
I have the same problem as well

**Comment by josejuanqm** [comment]
@IpareSe @adaminspaceship are you experiencing this issue with the demo project as well?

**Comment by adaminspaceship** [comment]
No. Only in my code when I implement it in my project

**Comment by krtliv** [comment]
same problem here, i have a small view of VersaPlayer inside a xib  after you press fullscreen the player cannot return back to the original constraints-frame.

**Comment by josejuanqm** [comment]
@adaminspaceship , @krtliv is the initial view removed from its superview?

**Comment by cemalsayin** [comment]
I saw same bug, i changed official example project's player frames and yes when click fullscreen button for turn back my view(close full screen mode) it didn't.

**Comment by fadizant** [comment]
To avoid this issue you have to add VersaPlayerView inside other view and add all edges constrains to new superview

![image](https://user-images.githubusercontent.com/13743626/95501860-9e063380-09b1-11eb-949e-69cb1b9b2366.png)
